//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_RegDetails
    {
        public int appl_no { get; set; }
        public string veh_no { get; set; }
        public Nullable<int> veh_id { get; set; }
        public string owner_id { get; set; }
        public System.DateTime date_of_purchase { get; set; }
        public string distributer_name { get; set; }
    
        public virtual TM_OwnerDetails TM_OwnerDetails { get; set; }
        public virtual TM_VehicleDetails TM_VehicleDetails { get; set; }
    }
}
